name: deploy-to-ghPages
on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies 🛠
        run: yarn install --frozen-lockfile

      - name: Build 📦
        run: yarn run build
        env:
          API_URL: ${{secrets.API_URL}}
          PUBLIC_URL: ${{secrets.PUBLIC_URL}}
          WEBPACK_PUBLIC_PATH: ${{secrets.WEBPACK_PUBLIC_PATH}}

      #add tests here later

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
